<a href="https://colab.research.google.com/github/Gustavo-Michael/Mineria_178318/blob/main/largest_islands.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# World's largest islands

This dataset `largest-islands.csv` contains information about the 100 largest islands in the world. The unit for the `area` column is km2.

In [ ]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'largest-islands.csv'.

# from google.colab import files
# uploaded = files.upload()

In [1]:
from google.colab import files
uploaded = files.upload()

Saving largest-islands.csv to largest-islands.csv

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('largest-islands.csv')
df.head()

      region      island    area                countries    climate  rank
0     Africa  Madagascar  591896               Madagascar    tropics     4
1  Antarctic   Kerguelen    6200  Antarctic Lands, France  temperate    91
2       Asia       Sumba   11153                Indonesia    tropics    65
3       Asia      Hainan   34300                    China    tropics    37
4       Asia      Taiwan   36198                   Taiwan    tropics    36

### Project Ideas

- What are the 10 largest islands in the tropics?

- What are the largest islands in each `region`?

- Create a line graph with `area` on the y-axis and `rank` on the x-axis. The data should be ordered by `rank`, from largest to smallest.

- What islands are composed of multiple countries?
	- Hint: try `countries.str.contains(",")`

In [8]:
#LARGEST ISLANDS IN THE TROPICS

df_10 = df.sort_values(by='area', ascending=False)
df_10.head(10)

,region,island,area,countries,climate,rank
41,Europe,Greenland,2166086,Denmark,polar,1
86,Oceania,New Guinea,821400,"Papua New Guinea, Indonesia",tropics,2
23,Asia,Borneo,755000,"Indonesia, Malaysia, Brunei",tropics,3
0,Africa,Madagascar,591896,Madagascar,tropics,4
75,North America,Baffin Island,507451,Canada,polar,5
28,Asia,Sumatra,480793,Indonesia,tropics,6
27,Asia,Honshu,227898,Japan,temperate,7
69,North America,Victoria Island,217291,Canada,polar,8
43,Europe,Great Britain,209331,United Kingdom,temperate,9
83,North America,Ellesmere (Nunavut),196236,Canada,polar,10

In [10]:
# largest islands by region

df_region = df.sort_values(by='region')
df_region.head(10)

,region,island,area,countries,climate,rank
0,Africa,Madagascar,591896,Madagascar,tropics,4
1,Antarctic,Kerguelen,6200,"Antarctic Lands, France",temperate,91
29,Asia,Bangka,11330,Indonesia,tropics,62
28,Asia,Sumatra,480793,Indonesia,tropics,6
27,Asia,Honshu,227898,Japan,temperate,7
26,Asia,Luzon,104688,Philippines,tropics,17
25,Asia,Panay,11515,Philippines,tropics,61
24,Asia,Palawan,11785,Philippines,tropics,59
23,Asia,Borneo,755000,"Indonesia, Malaysia, Brunei",tropics,3
22,Asia,Sulawesi,188522,Indonesia,tropics,11